version: '2'

services:
    constanceteste_php_1:
        container_name: constanceteste_php_1
        build:
            context: ./build
            dockerfile: Dockerfile.dev
        volumes:
          - ./:/home/projeto
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:BWnSGDb4B9apVKelKw0GTvwzUUZx89166jKRX2eetNI=
            - APP_DEBUG=true
            - APP_LOG_LEVEL=debug
            - APP_URL=http://localhost

            - DB_CONNECTION=mysql
            - DB_HOST=servidor_mysql
            - DB_PORT=3306
            - DB_DATABASE=projeto
            - DB_USERNAME=root
            - DB_PASSWORD=yakTLS&70c52

            - BROADCAST_DRIVER=log
            - CACHE_DRIVER=file
            - SESSION_DRIVER=file
            - SESSION_LIFETIME=120
            - QUEUE_DRIVER=sync

            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

            - MAIL_DRIVER=smtp
            - MAIL_HOST=smtp.mailtrap.io
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null

            - PUSHER_APP_ID=
            - PUSHER_APP_KEY=
            - PUSHER_APP_SECRET=
            - PUSHER_APP_CLUSTER=mt1

            - NEW_RELIC_APP_NAME=laravel-crud-constance-teste 
            - NEW_RELIC_LICENCE=Licença-aqui
